Made attributesMapToString() to check attributes efficiency.
Synesthesias/libcitygml pull request #15
Opened 2022-07-08 08:53 UTC by linoal

2022-07-08 10:05 UTC, dazzhe commented on sources/include/citygml/attributesmap.h
>  LIBCITYGML_EXPORT std::ostream& operator<<(std::ostream& os, const AttributeValue& o);
AttributesMapのstreamのオーバーロードとして実装お願いします。

```suggestion
LIBCITYGML_EXPORT std::ostream& operator<<(std::ostream& os, const AttributeValue& o);
LIBCITYGML_EXPORT std::ostream& operator<<(std::ostream& os, const AttributesMap& o);
```

2022-07-08 10:06 UTC, dazzhe requested changes
PRありがとうございます。

一点だけコメントしましたので修正後マージお願いいたします。

2022-07-09 10:05 UTC, linoal commented
AttributesMap.operator<< のオーバーロードとして実装しました。

2022-07-09 10:12 UTC, linoal commented on sources/include/citygml/attributesmap.h
>  LIBCITYGML_EXPORT std::ostream& operator<<(std::ostream& os, const AttributeValue& o);
修正しました！

2022-07-11 05:02 UTC, merged